@url_dev=http://localhost:5000/v1/api

POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 4bab98e77c4344bbc7f0677359d051f6cae3d81676397c26454d1be93da5ab559b7fa08f83e907b2abcd73672cdca722c47c0fb377f278cce6e4b75788422048 
x-client-id: 66dc3e0ea3df481479899ac4
# authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmRjM2UwZWEzZGY0ODE0Nzk4OTlhYzQiLCJlbWFpbCI6InVzZXIxQGV4YW1wbGUuY29tIiwiaWF0IjoxNzI1NzA5ODQwLCJleHAiOjE3MjU4ODI2NDB9.UYGY4mK2xaKVmEGP5dN1Il7U-uCFphY8LLuZzSvEQM4DwVHuro4P5dsEcQsmZ_qi8B2wPXjQ8fLaOsuLh_rJqzgil7H---E8m2r3VwY2gcpsR-XrFPd_ya22jL1uqEdPOM34RF0kMiv-qAi4BypR_64npfTfS-4cUK-289pAfSN0ErjmQ8StfxyP_exqCEJYTus1BixkL1rz9gfEpCxdvNU7xD9ZAKFq-42U0LElzex01dRdGvRQdjqck9R6QENTgLYaZHLtAaXWdbxh0avUOM5jzfgjVB4Cl9tA9QI_ptwcaTs4jll6gJf1SIjEpXCg0o19MOHTnCWpVxfv-HMNQn4UhG-H8Mx6sWFtY31yn7Us6Ii0Pdk-4zJX5bWA7WwCwb240Tz3qBZ6GYr0ZkOkzm1AwJrcyqYV7vngCQdO2jf5ggDMGZqlsylyWh33jJQ94LIpKFmvcjWxaMyJsqEkeH2bZ4xc9gJrTfr3sspHrA2gXxw53d5tDik6v1CaefTCDznoXWKkSMqjFWrlWDSasuL3kRXDXFdFuQKhLGh8izkxv9-rkAuNawtYBALitClDoXeq1ilDNoO69S-1FkpIVzKpuMZgtkCdqbZCQ7c-7bwwbY1lEVP2yrbWIYB4nPnWNpu_vH0p7dYNUzJcjCsH7vO3u9tlgrHF19s5rD4ZdBc

{
    "email": "user1@example.com",
    "password": "123456"
}


